### ISSUE TITLE
Indicate in the examples that a CSS background is required on the panel...

### ISSUE THREAD

**Issue by al-the-x** [Mango/slideout#151]
As mentioned in #131 and discovered by countless others, I'm sure, the `.slideout-panel` element requires a non-transparent `background` property for the effect to work correctly. Otherwise, the `.slideout-menu` "appears" behind the `.slideout-panel` on `slideout.open()` while the panel slides away and does not "disappear" until the panel is finished moving on `slideout.close()`. Consider adding a `background-color` to `index.css` and comment annotations to indicate this requirement, just for clarity. Happy to submit a PR.

**Comment by al-the-x** [comment]
Minimally:

```css
body {
  background-color: #FFF;
}

.slideout-panel {
  background-color: inherit;
}
```

Otherwise, the `height` of the `.slideout-panel` element may be smaller than the `height` of the `body` element / viewport and not carry the `background-color` to the bottom edge of the window.

**Comment by kerns** [comment]
I also think the "complete example" on the front page could use a re-write. Little details, like the `.slideout-menu` and `.slideout-panel` classes from the example CSS not being applied in the example HTML seems odd.

**Comment by felics** [comment]
@kerns They get applied by the script itself, there is no need to apply them in your HTML

**Comment by kerns** [comment]
@felics But, and this might be because I'm doing it wrong – but if I don't apply `.slideout-menu` in HTML I get a momentary view of the un-hidden/un-styled menu... before the JS has had time to apply the class that will hide it.

I could of course duplicate rules from `.slideout-menu` into another class and apply that one in HTML...but it seems redundant.

I'm sure there is a good reason it's structured this way, and why you don't just apply the most basic rules needed to setup and hide the menu to `#menu` which is already there and addressable ...I just don't know what those reasons are. :-)
