### ISSUE TITLE
Bug when sliding at 45 degrees

### ISSUE THREAD

**Issue by overben** [Mango/slideout#18]
The content is dragged not only horizontally but vertically also when sliding at 45 degrees..
Also you can't slide the menu just after scrolling in the page

Tested on iPhone 5. I posted some screenshots of the first bug.
![slide 45deg bug (1)](https://cloud.githubusercontent.com/assets/5367205/6530552/1d70843e-c432-11e4-97a3-48573789bf37.PNG)
![slide 45deg bug (2)](https://cloud.githubusercontent.com/assets/5367205/6530557/2670ad98-c432-11e4-9668-f2a808bd4692.PNG)

**Comment by talymo** [comment]
Cannot duplicate bug on iPhone 5 version 8.13 using Safari browser.

**Comment by voigtan** [comment]
I kinda have the same issue, if you try to drag the panel with a 45degrees angle (up and right) it will have a very strange animation.

**Comment by billcolumbia** [comment]
It seems to be an issue with Safari's bottom nav bar hiding itself, as the dom is animated/repainted. It only happens when you are at the top of the page, or have the full menu bars (top & bottom) active.

For anyone with a more web-appy experience you could probably limit this by using `<meta name="viewport" content="minimal-ui">`

**Comment by pazguille** [comment]
Cannot reproduce this bug on iPhone 5 (v8.3) using Safari browser.

**Comment by Fulminant** [comment]
I have the same problem but fixed this next steps:

1. Remove width and height 100% from html.
2. Add overflow:hidden to .slideout-panel when the slideout is opened.
