### ISSUE TITLE
Does this work on iOS and Android running through PhoneGap?

### ISSUE THREAD

**Issue by akerman25** [Mango/slideout#193]
The code run perfectly in the browser on my computer, but when testing in the Phonegap Developer App on my iPhone 5 the slide out menu won't work.

**Comment by pazguille** [comment]
Hi @akerman25, Could you share more information? What error do you have?

**Comment by vernondegoede** [comment]
I'm using this plugin through Phonegap as well and it works for me. \

Did you get any error messages? Did slideout load in the DOM at all?

**Comment by jolugama** [comment]
I have the same problem as @akerman25. In android witch phonegap not working. the touch event is not firing. don't show any error. why?

**Comment by jolugama** [comment]
I found the problem, at least on android. The problem was the version of android, specifically the kitkat version. I upgraded to lolipop and it works perfectly. There is a generic error in the handling of touch events in versions prior to lolipop.

I suggest that for the IOS version, the software should be upgraded to the latest version.

thanks and.... awesome!
