### ISSUE TITLE
only parts of the menu slides smoothly in/out

### ISSUE THREAD

**Issue by so-ri** [Mango/slideout#194]
Hello,

If opening/closing the Slideout, the header and the footer open/close smoothly in/out, but not the main content. You can watch it on https://kw.wesign.ch.

For testing, I've copied the demo-file on the end of the .readme and turned the background red - it didn't work neither like in your demo on https://mango.github.io/slideout/.

I hope you can help me. 

thank you and best regards,

**Comment by nimashoghi** [comment]
I'm also having this problem using this alongside Bootstrap 4.

**Comment by lmi11** [comment]
I have this issue too. I use Bootstrap 3.

**Comment by pazguille** [comment]
Hi @so-ri, I think the problem is with your layout heights. The height of the main content is more less than the navigation's height, so when you open / close the slideout you see this issue.

1. You could use `beforeopen` and `beforeclose` events to update the main content height to 100%.

2. You could add `height: 100%` to the  `<html>`.

Also, your `.container` should have a background color.
