### ISSUE TITLE
Full Example: Add snippet to open/close slideout clicking on a button.

### ISSUE THREAD

**Issue by pazguille** [Mango/slideout#41]
```js
document.querySelector('#panel button').addEventListener('click', function() {
  slideout.toggle();
});
```

**Comment by Joseffb** [comment]
<a href="javascript: void(0); slideout.toggle();">link/button</a> works too :)

**Comment by dahlskebank** [comment]
I'm kinda a noob when it comes to jQuery, but what is the difference from what @pazguille posted and what I use below?

$(".slideout-left-toggle").click(function(event) {
	event.preventDefault();
	slideout.toggle();
});

**Comment by Joseffb** [comment]
It's basically the same if not technically more of a preferred way of doing things in terms of jQuery style.

The $ calls the jquery library, the (".blah") identifies the object by class (# for id); .click is the hook/event listener to use, then you pop an anonymous function to run when it triggers. Inside the function you tell it to ignore the events default action (ie a would otherwise try to follow href location), then you call the slide out function.

Should all just work.

Thing to remember is that for anything you can do with jQuery their is at least one other way of doing it, not to mention hybrid ways as well.

Happy Easter!

__
Get to know me, check out my website: http://joseffb.me
