### ISSUE TITLE
What is 'tolerance' option?

### ISSUE THREAD

**Issue by MikeSha** [Mango/slideout#68]
Hi guys,

I have a silly question. What is 'tolerance' option? I can't see any effect :)

**Comment by Charpeni** [comment]
The tolerance option is to determine when you release the touch if the menu should open or close.

For example, with low tolerance you only need to slide a little bit at the menu and release it opens. With a high tolerance, you need more drag the menu to open it, otherwise it closes.

I don't know if this is clear, but this is literally the number of px needed for the menu can be opened completely, otherwise it closes.

```javascript
(self._opening && Math.abs(self._currentOffsetX) > self._tolerance) ? self.open() : self.close();
```
